import { isoFromNow, todayIso } from "@/lib/format";
import type { WorkshopState } from "@/lib/types";

export function createSeedState(): WorkshopState {
  return {
    clients: [
      {
        id: "c1",
        name: "Ana Paula Souza",
        phone: "11987654321",
        city: "São Paulo",
        notes: "Dona da Boutique Flores. Prefere linho e cores terrosas. Retira no ateliê.",
        createdAt: isoFromNow(-40),
      },
      {
        id: "c2",
        name: "Carlos Henrique Lima",
        phone: "11976543210",
        city: "Guarulhos",
        notes: "Uniformes Lima. Pedidos grandes, precisa de grade completa. Paga no Pix após entrega.",
        createdAt: isoFromNow(-55),
      },
      {
        id: "c3",
        name: "Maria Clara Ribeiro",
        phone: "19998761122",
        city: "Campinas",
        notes: "Cliente particular. Gosta de prova antes do acabamento.",
        createdAt: isoFromNow(-18),
      },
      {
        id: "c4",
        name: "Escola Estrelinha",
        phone: "1134567890",
        city: "Osasco",
        notes: "Contato: coordenadora Helena. Uniformes com logo bordado no peito.",
        createdAt: isoFromNow(-12),
      },
      {
        id: "c5",
        name: "Juliana Mendes",
        phone: "21988884455",
        city: "Rio de Janeiro",
        notes: "Loja JM. Envio via malote nas quintas.",
        createdAt: isoFromNow(-70),
      },
      {
        id: "c6",
        name: "Pedro Santos",
        phone: "11912345566",
        city: "São Paulo",
        notes: "Restaurante Barolo. Aventais e camisetas da equipe.",
        createdAt: isoFromNow(-8),
      },
    ],
    orders: [
      {
        id: "o1",
        number: "PED-012",
        clientId: "c1",
        stage: "costura",
        dueDate: isoFromNow(2),
        deliveryDate: isoFromNow(2),
        deliveredAt: null,
        notes: "Barra italiana. Fecho invisível nas costas.",
        createdAt: isoFromNow(-9),
        items: [
          {
            id: "i1a",
            description: "Vestido midi",
            fabric: "Linho misto",
            color: "Areia",
            size: "M",
            quantity: 2,
            unitPrice: 280,
          },
          {
            id: "i1b",
            description: "Vestido midi",
            fabric: "Linho misto",
            color: "Terracota",
            size: "G",
            quantity: 2,
            unitPrice: 280,
          },
        ],
      },
      {
        id: "o2",
        number: "PED-013",
        clientId: "c2",
        stage: "corte",
        dueDate: isoFromNow(5),
        deliveryDate: isoFromNow(6),
        deliveredAt: null,
        notes: "Logo bordado no peito esquerdo. Grade: 4P 8M 8G.",
        createdAt: isoFromNow(-4),
        items: [
          {
            id: "i2a",
            description: "Camisa polo uniforme",
            fabric: "Piquet",
            color: "Marinho",
            size: "Grade",
            quantity: 20,
            unitPrice: 78,
          },
        ],
      },
      {
        id: "o3",
        number: "PED-014",
        clientId: "c3",
        stage: "acabamento",
        dueDate: todayIso(),
        deliveryDate: todayIso(),
        deliveredAt: null,
        notes: "Festa no sábado. Decote V, forro completo. Prova já aprovada.",
        createdAt: isoFromNow(-16),
        items: [
          {
            id: "i3a",
            description: "Vestido de festa",
            fabric: "Crepe com tule",
            color: "Verde musgo",
            size: "P",
            quantity: 1,
            unitPrice: 890,
          },
        ],
      },
      {
        id: "o4",
        number: "PED-015",
        clientId: "c4",
        stage: "aprovado",
        dueDate: isoFromNow(14),
        deliveryDate: isoFromNow(14),
        deliveredAt: null,
        notes: "Aguardar tecido do fornecedor (previsão sexta). Bordado do brasão incluso.",
        createdAt: isoFromNow(-3),
        items: [
          {
            id: "i4a",
            description: "Conjunto escolar (camiseta + short)",
            fabric: "Malha PV",
            color: "Azul royal",
            size: "Infantil",
            quantity: 40,
            unitPrice: 62,
          },
        ],
      },
      {
        id: "o5",
        number: "PED-010",
        clientId: "c5",
        stage: "entregue",
        dueDate: isoFromNow(-8),
        deliveryDate: isoFromNow(-8),
        deliveredAt: isoFromNow(-7),
        notes: "Enviado no malote de quinta.",
        createdAt: isoFromNow(-21),
        items: [
          {
            id: "i5a",
            description: "Blusa manga bufante",
            fabric: "Viscose",
            color: "Off-white",
            size: "M",
            quantity: 6,
            unitPrice: 95,
          },
          {
            id: "i5b",
            description: "Blusa manga bufante",
            fabric: "Viscose",
            color: "Preto",
            size: "G",
            quantity: 6,
            unitPrice: 95,
          },
        ],
      },
      {
        id: "o6",
        number: "PED-016",
        clientId: "c6",
        stage: "orcamento",
        dueDate: isoFromNow(10),
        deliveryDate: isoFromNow(10),
        deliveredAt: null,
        notes: "Enviar orçamento com e sem bordado do nome do restaurante.",
        createdAt: isoFromNow(-1),
        items: [
          {
            id: "i6a",
            description: "Avental peitoral",
            fabric: "Brim",
            color: "Preto",
            size: "Único",
            quantity: 8,
            unitPrice: 54,
          },
        ],
      },
      {
        id: "o7",
        number: "PED-011",
        clientId: "c1",
        stage: "pronto",
        dueDate: isoFromNow(-1),
        deliveryDate: todayIso(),
        deliveredAt: null,
        notes: "Aguardando retirada. Já avisada no WhatsApp ontem.",
        createdAt: isoFromNow(-14),
        items: [
          {
            id: "i7a",
            description: "Saia envelope",
            fabric: "Alfaiataria",
            color: "Caramelo",
            size: "M",
            quantity: 3,
            unitPrice: 160,
          },
          {
            id: "i7b",
            description: "Saia envelope",
            fabric: "Alfaiataria",
            color: "Caramelo",
            size: "G",
            quantity: 3,
            unitPrice: 160,
          },
        ],
      },
      {
        id: "o8",
        number: "PED-009",
        clientId: "c2",
        stage: "costura",
        dueDate: isoFromNow(-4),
        deliveryDate: isoFromNow(-2),
        deliveredAt: null,
        notes: "ATRASADO. Faltou linha da cor — chegou hoje. Prioridade na máquina 2.",
        createdAt: isoFromNow(-18),
        items: [
          {
            id: "i8a",
            description: "Calça social uniforme",
            fabric: "Twill",
            color: "Chumbo",
            size: "Grade",
            quantity: 15,
            unitPrice: 110,
          },
        ],
      },
    ],
    payments: [
      {
        id: "p1",
        orderId: "o1",
        amount: 560,
        date: isoFromNow(-8),
        method: "pix",
        note: "Sinal 50%",
      },
      {
        id: "p2",
        orderId: "o3",
        amount: 890,
        date: isoFromNow(-10),
        method: "pix",
        note: "Pagamento integral na aprovação",
      },
      {
        id: "p3",
        orderId: "o4",
        amount: 744,
        date: isoFromNow(-2),
        method: "transferencia",
        note: "Sinal 30%",
      },
      {
        id: "p4",
        orderId: "o5",
        amount: 1140,
        date: isoFromNow(-7),
        method: "pix",
        note: "Quitado na entrega",
      },
      {
        id: "p5",
        orderId: "o7",
        amount: 960,
        date: isoFromNow(-3),
        method: "pix",
        note: "",
      },
      {
        id: "p6",
        orderId: "o8",
        amount: 800,
        date: isoFromNow(-15),
        method: "boleto",
        note: "Entrada",
      },
    ],
  };
}
