/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as RapidoRouteImport } from './routes/rapido'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as PedidosNovoRouteImport } from './routes/pedidos.novo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidoRoute = RapidoRouteImport.update({
  id: '/rapido',
  path: '/rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PedidosRoute,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PedidosRoute,
} as any)
const PedidosNovoRoute = PedidosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => PedidosRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRouteWithChildren
  '/producao': typeof ProducaoRoute
  '/rapido': typeof RapidoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/producao': typeof ProducaoRoute
  '/rapido': typeof RapidoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRouteWithChildren
  '/producao': typeof ProducaoRoute
  '/rapido': typeof RapidoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/conta'
    | '/financeiro'
    | '/login'
    | '/pedidos'
    | '/producao'
    | '/rapido'
    | '/clientes/$id'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/clientes/'
    | '/pedidos/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta'
    | '/financeiro'
    | '/login'
    | '/producao'
    | '/rapido'
    | '/clientes/$id'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/clientes'
    | '/pedidos'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/conta'
    | '/financeiro'
    | '/login'
    | '/pedidos'
    | '/producao'
    | '/rapido'
    | '/clientes/$id'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/clientes/'
    | '/pedidos/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ContaRoute: typeof ContaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  PedidosRoute: typeof PedidosRouteWithChildren
  ProducaoRoute: typeof ProducaoRoute
  RapidoRoute: typeof RapidoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapido': {
      id: '/rapido'
      path: '/rapido'
      fullPath: '/rapido'
      preLoaderRoute: typeof RapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof PedidosRoute
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof PedidosRoute
    }
    '/pedidos/novo': {
      id: '/pedidos/novo'
      path: '/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof PedidosNovoRouteImport
      parentRoute: typeof PedidosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface PedidosRouteChildren {
  PedidosIdRoute: typeof PedidosIdRoute
  PedidosNovoRoute: typeof PedidosNovoRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

const PedidosRouteChildren: PedidosRouteChildren = {
  PedidosIdRoute: PedidosIdRoute,
  PedidosNovoRoute: PedidosNovoRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}

const PedidosRouteWithChildren =
  PedidosRoute._addFileChildren(PedidosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ContaRoute: ContaRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  PedidosRoute: PedidosRouteWithChildren,
  ProducaoRoute: ProducaoRoute,
  RapidoRoute: RapidoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
